[features]
seeds = false
skip-lint = false
[programs.localnet]
savings_vault = "HfJVM6Ayjajt9H58AZoCFqkCQQFehSeQfGQbi3crxT8W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/0xabstracted/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
